#!/usr/bin/env node
/**
 * Builds ebook/index.html — a single, self-contained, offline interactive
 * edition of "The AI Income Blueprint".
 *
 * The book's text lives in one place only: prisma/seed-data.ts, which also
 * feeds the Next.js academy's database seed. This script reads that file
 * directly (stripping its handful of TypeScript annotations so plain Node can
 * import it), reshapes it for the reader, and inlines the result into
 * ebook/template.html.
 *
 * Usage:  node ebook/build.mjs        (or: npm run ebook:build)
 * No dependencies, no install step required.
 */
import { readFile, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

const SEED = join(root, "prisma", "seed-data.ts");
const TEMPLATE = join(here, "template.html");
const OUT = join(here, "index.html");

const BOOK_META = {
  author: "Hassan Mohammed",
};

/** Load seed-data.ts as an ES module by removing its TypeScript-only syntax. */
async function loadSeed() {
  const ts = await readFile(SEED, "utf8");
  const js = ts
    .replace(/^export type [\s\S]*?^};$/gm, "") // the four `export type X = {...};` blocks
    .replace(/^export const modules: SeedModule\[\] =/m, "export const modules =");

  if (/:\s*(string|number|boolean|SeedModule|SeedLesson|SeedQuestion)\b/.test(js)) {
    throw new Error(
      "seed-data.ts contains TypeScript annotations this script doesn't strip.\n" +
      "Update loadSeed() in ebook/build.mjs to handle them."
    );
  }
  const url = "data:text/javascript;base64," + Buffer.from(js).toString("base64");
  return import(url);
}

/** "Chapter 7: Selling AI-Generated Digital Products" -> { number: 7, short: "Selling…" } */
function splitTitle(title, fallbackNumber) {
  const m = title.match(/^Chapter\s+(\d+)\s*[:—-]\s*(.+)$/);
  return m
    ? { number: Number(m[1]), short: m[2].trim() }
    : { number: fallbackNumber, short: title };
}

function buildBook({ course, modules }) {
  let n = 0;
  const parts = modules.map(mod => ({
    slug: mod.slug,
    title: mod.title,
    description: mod.description,
    chapters: mod.lessons.map(lesson => {
      const { number, short } = splitTitle(lesson.title, ++n);
      n = number;
      return {
        slug: lesson.slug,
        number,
        title: lesson.title,
        shortTitle: short,
        partTitle: mod.title,
        summary: lesson.summary,
        body: lesson.content,
        minutes: lesson.estMinutes,
        takeaways: lesson.keyTakeaways ?? [],
        caseStudy: lesson.caseStudy ?? null,
        actionStep: lesson.actionStep ?? null,
        quiz: (lesson.quiz ?? []).map(q => ({
          prompt: q.prompt,
          choices: q.choices,
          answer: q.answer,
        })),
      };
    }),
  }));

  return {
    title: course.title,
    subtitle: course.subtitle,
    description: course.description,
    author: BOOK_META.author,
    parts,
  };
}

/** JSON that is safe to inline inside a <script> element. */
function inlineJSON(value) {
  return JSON.stringify(value)
    .replace(/</g, "\\u003c")
    .replace(/>/g, "\\u003e")
    .replace(/\u2028/g, "\\u2028")
    .replace(/\u2029/g, "\\u2029");
}

const seed = await loadSeed();
const book = buildBook(seed);
const template = await readFile(TEMPLATE, "utf8");

const PLACEHOLDER = "/*__BOOK_DATA__*/null/*__END_BOOK_DATA__*/";
if (!template.includes(PLACEHOLDER)) {
  throw new Error(`template.html is missing the ${PLACEHOLDER} placeholder.`);
}

const html = template
  .replace(PLACEHOLDER, () => inlineJSON(book)) // function form: no `$&` expansion
  .replace(
    "<head>",
    `<head>\n<!-- Generated by ebook/build.mjs from prisma/seed-data.ts. Edit template.html or the seed data, then re-run: npm run ebook:build -->`
  );

await writeFile(OUT, html, "utf8");

const chapters = book.parts.flatMap(p => p.chapters);
console.log(
  `ebook/index.html written — ${book.parts.length} parts, ${chapters.length} chapters, ` +
  `${chapters.reduce((t, c) => t + c.quiz.length, 0)} quiz questions, ` +
  `${(Buffer.byteLength(html) / 1024).toFixed(0)} KB`
);
